spring.application.name=vacunacion-adultos
spring.profiles.active=dev

# ── Servidor ─────────────────────────────────────────────────────────────────
server.port=8080
server.tomcat.connection-timeout=120000
server.tomcat.keep-alive-timeout=120000

